In [1]:
import numpy as np

In [2]:
### loops are slow in Python
# Example

arr = np.array([1, 2, 3, 4 ,5, 6, 7, 8, 9])

result = []

for i in arr:
    result.append(i**2)
print(result)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [8]:
### We use Numpy for fast 
# Vectorization

arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
result = arr**2
print(result)

[ 1  4  9 16 25 36 49 64 81]


In [10]:
### Broadcasting with scaler

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = arr1 + 10
print(arr2)

[11 12 13 14 15]


In [11]:
### Broadcasting arrays with different shape (vector)

arr3 = np.array([1, 2, 3, 4, 5])
arr4 = np.array([1, 2, 3, 4, 5])

result = arr3 + arr4
print(result)

[ 2  4  6  8 10]


In [13]:
### nroadcasting arr5 across arr6

arr5 = np.array([[1, 2, 3], [4, 5, 6]])
arr6 = np.array([1, 2, 3])
result = arr5 + arr6

print(result)

[[2 4 6]
 [5 7 9]]


In [15]:
### Normalized data using broadcasting

data = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])

mean = data.mean(axis=0)
std = data.std(axis=0)

result = (data - mean)/std

print(result)



[[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]
