In [1]:
import numpy as np

In [23]:
arr = np.array([1, 2, 3, 4, 5])

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [6]:
#1. Mean
np.mean(arr)

3.0

In [7]:
#2. min
np.min(arr)

1

In [8]:
#3. max
np.max(arr)

5

In [9]:
#4. variance
np.var(arr)

2.0

In [10]:
#5. Standardization
np.std(arr)

1.4142135623730951

In [11]:
#6. Sum
np.sum(arr)

15

In [12]:
#7. Product(mul)
np.prod(arr)

120

In [19]:
#8. Median
np.median(arr)

3.0

In [15]:
#9. Percentile (%)
np.percentile(arr, 27) # 27 is percentile

2.08

In [16]:
#10. Index of minimum value in array
np.argmin(arr) # It prints index

0

In [17]:
#11. Index of maximum valur=e in array
np.argmax(arr) # It prints index

4

In [24]:
#12. Correlation-Co-efficient
np.corrcoef(arr1, arr2)

array([[1., 1.],
       [1., 1.]])

In [26]:
#13. Unique element of an array
np.unique(arr) # It removes the duplicates elements in an array

array([1, 2, 3, 4, 5])

In [30]:
#14 Compute the n-th differences of an array.
np.diff(arr)

array([1, 1, 1, 1])

In [37]:
#15. Compute the cumulative sum of an array.
np.cumsum(arr) # Adds elements one by one forward

array([ 1,  3,  6, 10, 15])

In [38]:
#16. reate an array with evenly spaced numbers over a specified interval.
np.linspace(0, 5, 3)

array([0. , 2.5, 5. ])

In [39]:
#17. Compute the natural logarithm of an array.
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [40]:
#18. Compute the exponential of an array.
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [41]:
###########################################################################################################