In [1]:
import numpy as np

In [3]:
### Indexing

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12]])
arr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
flattened = arr.flatten()
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
flattened[0]

1

In [7]:
flattened[:5]

array([1, 2, 3, 4, 5])

In [8]:
flattened[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
### Slicing in NumPy Array

flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
b = flattened[2:5]
b

array([3, 4, 5])

In [16]:
b[0] = 27 # We change the value at index 0 is 3 to 27
b

array([27,  4,  5])

In [17]:
flattened  # instead of getting copy of original array it gives us updated array

array([ 1,  2, 27,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
# Now we can create a copy of orif+ginal array
# by using the .copy() method

b = flattened[2:5].copy()
b

array([27,  4,  5])

In [23]:
b[0] = 1027
b

array([1027,    4,    5])

In [24]:
flattened # Now see the original array is not changed instead it creates a new array

array([ 1,  2, 27,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
### Fancy indexing

arr1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
idx = [[0, 2, 5, 7, 9]]
print(arr1[idx])

[[ 10  30  60  80 100]]


In [38]:
### Boolean masking

arr2 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
mask = arr2 > 40

print(arr2[mask])

[ 50  60  70  80  90 100]
