In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Accessing an element

arr[0][1]    # 0'th row & 1'th column 

2

In [9]:
arr[0:2, 1:3] # Extracting elements in an array (0 & 1 - row and 2 & 3 - column)

array([[2, 3],
       [5, 6]])

In [10]:
### Inndexing in 3D arrays

arr1 = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
# 1st depth | 2nd row | 3rd column

arr1[ : , 0, : ] # OUTPUT: 0'th row and every column

array([[1, 2, 3],
       [7, 8, 9]])

In [20]:
### Practical example : Select data along axes

# Get all row in 1st column

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
arr[:, 0]

array([1, 4, 7])

In [22]:
# 1st row in each "sheet" in 3D array

arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr1[:, 0, :]

array([[1, 2, 3],
       [7, 8, 9]])

In [27]:
# Changing data along an axes

arr1

array([[[ 7,  7,  7],
        [ 4,  5,  6]],

       [[ 7,  7,  7],
        [10, 11, 12]]])

In [28]:
arr1[:, 0, :] = 7
arr1

array([[[ 7,  7,  7],
        [ 4,  5,  6]],

       [[ 7,  7,  7],
        [10, 11, 12]]])