In [3]:
import numpy as np

In [4]:
!pip install numpy           # installing command NumPy 

In [38]:
### Types of Arrays

np.array([1, 2, 3])          # normal NumPy Array

array([1, 2, 3])

In [39]:
np.zeros((2, 3))              # Zero's array


array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.ones((1, 3, 4))            # Ones's Array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [41]:
np.full((3, 4), 4)            # Full Array (for perticular num)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [42]:
np.eye(7)                     # Eye Array (like Identical matrix)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [43]:
np.arange(0, 100, 7) # A-range Array (start from 1st element, middle element is limit, end element distance)

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [44]:
np.linspace(0, 27, 4)  # Lin-space Array (start from 1st element, middle element is limit, end element is no. of element being executed)

array([ 0.,  9., 18., 27.])

In [50]:
### NumPy Array properties

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [51]:
np.zeros((3, 3))    # Array of Zero's

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.ones((3, 4))     # Array of One's

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
np.full((2, 4), 7)  # Array filled with 7

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [56]:
np.eye(7)           # Identity matrix

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [59]:
np.arange(0, 71, 7) # A-range Array (like range)

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [65]:
np.linspace(1, 100, 10) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [102]:
### Check Array properties

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12]])
arr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [103]:
arr.shape # Shape of Array

(4, 3)

In [104]:
arr.size # Size of Array

12

In [105]:
arr.ndim # Dimension of Array

2

In [106]:
arr.dtype # int64 or "int32 for Windows"

dtype('int32')

In [107]:
### Chnaging data type

arr1 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]], dtype=np.float32)  # Explicit type
arr1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [108]:
arr1.dtype

dtype('float32')

In [109]:
arr_int = arr1.astype(np.int32)           # Convert float to int
print(arr_int)

arr_int.dtype

[[1 2 3]
 [4 5 6]
 [7 8 9]]


dtype('int32')

In [110]:
arr2 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
n = arr.astype('float64')
n.dtype

dtype('float64')

In [112]:
print(arr1.dtype)
print(arr2.dtype)

float32
int32


In [116]:
### Reshaping and flattering Arrays

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr.shape

(4, 3)

In [117]:
reshaped = arr.reshape((3,4))
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [118]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [120]:
reshaped1 = arr.reshape((2, 6))       # Note: The mul of row & col should be the same 
reshaped1               

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [122]:
flattened = arr.flatten()            # It convert any dimentional arry to "1D".
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [126]:
# Example any dimensional Array to 1D array

arr3 = np.array([[[1, 2], [3, 4]], [[5, 6],[7, 8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [127]:
arr3.ndim

3

In [128]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])