In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr.dtype

dtype('int32')

In [5]:
arr2 = arr.astype("float64")
arr2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [9]:
arr3 = arr2.astype(np.int32) 
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr4 = arr3.astype("float64")
arr4

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [13]:
arrf = np.array([[1, 2, 3,], [4, 5, 6]], dtype = "float64")
arrf

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
### Downcasting 

arr_large = np.array([[1, 2, 3,], [4, 5, 6]], dtype = "float64")
arr_large

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
arr_small = arr_large.astype(np.int32)
print(arr_small)
print(arr_small.dtype)

[[1 2 3]
 [4 5 6]]
int32


In [21]:
### Why data types are matter kin NUmPy

arr_int64 = np.array([[1, 2, 3], [4, 5 ,6]], dtype=np.int64)
arr_int32 = np.array([[1, 2, 3], [4, 5 ,6]], dtype=np.int32)

print(arr_int64.nbytes) # Less memory size usage
print(arr_int32.nbytes) # More memory size usage

48
24


In [22]:
### String in NumPy
# Note: Using string in NumPy is not a good idea

str = np.array(['Apple', 'Banana', 'Mango'], dtype = 'U10') # Instead of 'U10' also 'str'.
print(str)

['Apple' 'Banana' 'Mango']


In [30]:
### Complex Numbers

compl = np.array([[1 + 2j], [2 + 3j]], dtype = 'complex64')
print(compl)

[[1.+2.j]
 [2.+3.j]]


In [33]:
### Object data type (Mixed)

obj = np.array([[1, 2, 3], 'mayur', 1], dtype = 'object')
print(obj)         # it gives list

[list([1, 2, 3]) 'mayur' 1]
