In [5]:
import numpy as np

### Exercises for Practice
    # Create a 3×3 array filled with random numbers and print its shape.
    # Convert an array of floats [1.1, 2.2, 3.3] into integers.
    # Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
    # Reshape a 1D array of size 9 into a 3×3 matrix.
    # Use boolean masking to filter numbers greater than 50 in an array.

In [7]:
 # Create a 3×3 array filled with random numbers and print its shape.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.shape

(3, 3)

In [9]:
# Convert an array of floats [1.1, 2.2, 3.3] into integers.

arr2 = np.array([1.1, 2.2, 3.3])
arr2

array([1.1, 2.2, 3.3])

In [13]:
into_int = arr2.astype(np.int32)
into_int

array([1, 2, 3])

In [22]:
# Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

arr3 = np.array([1, 2, 3, 4, 5, 6])
idx = [[1, 3, 5]]
print(arr3[idx])

[[2 4 6]]


In [23]:
# Reshape a 1D array of size 9 into a 3×3 matrix.

arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr4.ndim

1

In [25]:
reshaped = arr4.reshape(3, 3)
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Use boolean masking to filter numbers greater than 50 in an array.

