In [34]:
# Using Python Lists
import numpy as np
import time

size = 1_000_0000    # we use the "_" for better code reading
l1 = list(range(size))
l2 = list(range(size))

start = time.time() # Start time
add = (x+y for x, y in zip(l1, l2)) # zipping
end = time.time()   # End time

print(end - start)  # subtract final time - initial time 

# The output of the SpeedTeest of List is "0.7060768604278564".

0.7060768604278564


In [32]:
import numpy as np
import time

size = 1_000_0000    # we use the "_" for better code reading
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time() # Start time
add = l1 + l2       # No need to use loop in numpy
end = time.time()   # End time

print(end - start)  # subtract final time - initial time 

# The output of the SpeedTeest of NumPy is "0.04430651664733887".

0.04430651664733887


In [41]:
np.array([1, 2, 3, 4])                    # 1D dimensional array

array([1, 2, 3, 4])

In [42]:
np.array([[1, 2], [3,4], [5, 6]])         # 2D array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
arr  = np.array([[1,2, 3], [5, 6, 7], [7,8, 9]]) # 3D array
arr

array([[1, 2, 3],
       [5, 6, 7],
       [7, 8, 9]])

In [51]:
# Check type
type(arr)

numpy.ndarray

In [52]:
arr.shape # Output: (3, 3) --> 3-rows & 3-columns

(3, 3)

In [66]:
# Memory Efficiency

import sys      # For list

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:",sys.getsizeof(list_data) + sum(sys.getsizeof(item) for item in list_data), "bytes")

print("NumPy array size:", numpy_data.nbytes, "bytes") 

# total_size = sys.getsizeof(list_data) + sum(sys.getsizeof(item) for item in list_data)


Python list size: 36056 bytes
NumPy array size: 4000 bytes


In [65]:
# Vecorization - No more loops

# Python list (loop-based)
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

start = time.time()
list_squares = [x ** 2 for x in list1]
end = time.time()
print(f"Time taken is: {start - end} sec")

print(list_squares)

# NumPy (vectorized)
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

start = time.time()
numpy_squares = arr1 ** 2
end = time.time()
print(f"Time taken is: {start - end} sec")

print(numpy_squares)

Time taken is: 0.0 sec
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
Time taken is: -0.0014743804931640625 sec
[  1   4   9  16  25  36  49  64  81 100]


In [54]:
l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]

print(list(zip(l1, l2))) # "zip()" used to zip the list and execute output as tuple

[(1, 5), (2, 6), (3, 7), (4, 8)]
